### ISSUE TITLE
Breaks if excel has bold/italic text

### ISSUE THREAD

**Issue by MarcelRobitaille** [onerobotics/fexcel#6] opened 2019-07-18 20:39 UTC
When a spreadsheet has styled text (bold, italics), the program throws a SIGSEGV signal.

Steps to reproduce:
1. Compile fexcel 1.1.0 with go1.8 on Ubuntu 16.04.6 (Windows subsystem for Linux).
1. Create a new excel file (`.xlsx`).
1. Add a bit of text in A1 and style it bold or italic.
1. Run `fexcel` using the new excel file.
Removing the formatting and saving makes the script exit normally again. I was not able to reproduce on my Arch Linux machine with 1.12.

Full output:
```
  __                  _
 / _|                | |
| |_ _____  _____ ___| |
|  _/ _ \ \/ / __/ _ \ |
| ||  __/>  < (_|  __/ |
|_| \___/_/\_\___\___|_|
                  v1.1.0

by ONE Robotics Company
www.onerobotics.com

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x63651b]

goroutine 1 [running]:
github.com/360EntSecGroup-Skylar/excelize.(*File).formattedValue(0xc4200e48c0, 0x1, 0xc4201c8644, 0x4, 0x0, 0x67d420)
        /home/marcel/work/src/github.com/360EntSecGroup-Skylar/excelize/cell.go:557 +0x4b
github.com/360EntSecGroup-Skylar/excelize.(*xlsxC).getValueFrom(0xc420098400, 0xc4200e48c0, 0xc4200192c0, 0x2, 0xc4201a5330, 0x2, 0x2)
        /home/marcel/work/src/github.com/360EntSecGroup-Skylar/excelize/rows.go:316 +0x15c
github.com/360EntSecGroup-Skylar/excelize.(*File).GetCellValue.func1(0xc4200e28c0, 0xc420098400, 0xc4201c81a0, 0x2, 0x1, 0x0, 0x0)
        /home/marcel/work/src/github.com/360EntSecGroup-Skylar/excelize/cell.go:39 +0x55
github.com/360EntSecGroup-Skylar/excelize.(*File).getCellStringFunc(0xc4200e48c0, 0x6fc479, 0x6, 0xc4201a5330, 0x2, 0xc420169a60, 0x8, 0x10, 0xc4201a5310, 0x0)
        /home/marcel/work/src/github.com/360EntSecGroup-Skylar/excelize/cell.go:537 +0x2a5
github.com/360EntSecGroup-Skylar/excelize.(*File).GetCellValue(0xc4200e48c0, 0x6fc479, 0x6, 0xc4201a5330, 0x2, 0x0, 0x10, 0x68c560, 0xc420169a01)
        /home/marcel/work/src/github.com/360EntSecGroup-Skylar/excelize/cell.go:44 +0x84
github.com/onerobotics/fexcel/commenter.(*commenter).getIdAndComment(0xc4201ba360, 0x6fc479, 0x6, 0x1, 0x1, 0x0, 0x2, 0x0, 0x0, 0x48e7b2)
        /home/marcel/work/src/github.com/onerobotics/fexcel/commenter/commenter.go:74 +0x8c
github.com/onerobotics/fexcel/commenter.(*commenter).processColumn(0xc4201ba360, 0x7fffdcecc7af, 0x2, 0x1, 0x10, 0x0, 0x0, 0x1f4)
        /home/marcel/work/src/github.com/onerobotics/fexcel/commenter/commenter.go:239 +0x142
github.com/onerobotics/fexcel/commenter.(*commenter).Update(0xc4201ba360, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/marcel/work/src/github.com/onerobotics/fexcel/commenter/commenter.go:115 +0x7a
main.main()
        /home/marcel/work/src/fexcel/fexcel.go:167 +0x249
```

Before I go, I just want to express my huge appreciation for all the fanuc tools you have written. They have helped me out a lot. Thanks a bunch for sharing!

**Comment by unreal** [comment] 2019-07-18 20:45
The obvious solution is to not use **_formatting_**! :laughing:

Thanks for the bug report! I will attempt to reproduce and fix.

**Comment by MarcelRobitaille** [comment] 2019-07-19 00:27
Yeah it wasn't so obvious before I found the problem. That is what I am doing now. I am not desperate to get this fixed; I mostly posted the issue to serve as documentation for anyone experiencing the same issue.

**Comment by unreal** [comment] 2019-07-19 00:50
Sorry that was meant to be a joke. My bad. :/

I definitely appreciate the thorough report and will look into it tomorrow.

It seems like it may be an issue with the Excelize library itself, possibly architecture dependent.

**Comment by MarcelRobitaille** [comment] 2019-07-19 01:03
I know it was a joke. No hard feelings. Sorry if it seemed that way in my reply.

**Comment by unreal** [comment] 2019-07-26 15:39
Sorry for the long lag.

I've pushed a new branch that (I think) tests the issue, but I am unable to reproduce. Can you checkout the [formatting branch](https://github.com/onerobotics/fexcel/tree/formatting) and test via `go test ./commenter`?

You may also try using your fexcel build with the `./commenter/testdata/test.xlsx` spreadsheet's "Formatting" sheet which includes a bunch of formatting.

**Comment by unreal** [comment] 2020-01-09 17:46
I have not been able to reproduce this issue, but it seems to be an issue with excelize in this environment. Closing for now.

**Closed as completed by unreal** 2020-01-09 17:46 UTC
